### PR TITLE
Fix yarn dependencies

### PR DESCRIPTION
**Pull request by karolsojko**
Fixed missing yarn dependencies after merging: https://github.com/x-team/unleash/pull/316

/cc @gesposito @kdemoya

### CODE REVIEW

**Comment by kdemoya** [comment]
👍

**Comment by williamcabrera4** [comment]
Hi @karolsojko 
since we have this
`# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.`

Shouldn't we add this to the `.gitignore`  instead?
Since everything we add a new package will update the `package.json` and this `yarn.lock` file

**Comment by kdemoya** [comment]
Hey @williamcabrera4 Yarn uses the `yarn.lock` file to install the exact same dependency for everyone (similar to what a `npm-shrinkwrap` file do), it's actually mean to be in the repo if we want to get full advantage of Yarn.

**Comment by williamcabrera4** [comment]
@kdemoya 
Checking https://yarnpkg.com/en/docs/migrating-from-npm
Didn't know about that!! 😮 
You're right, very interesting concept there, so everyone have exactly the same.
Thanks Kelvin!

**Pull request merged**
