### PR TITLE
Add Profiles Style - fixes #223

### LINKED ISSUE #223: Fix list of profiles appearance
List of profiles is implemented in a simple way so it displays only names of users. 

It should reflect something as much as possible (regarding MaterialUI) similar to this: 
image

This means that every item should at least have the users photo/avatar on the left. As for the avatar urls you can get them from the response of Profiles API - the data is retrieved already but not displayed.

### PR DESCRIPTION
**Pull request by kdemoya**
Created new `UserCard` component to render users anywhere on the app with the user object from the API.

image

Looking at all those default images it came to my mind that we should have a default hero that we can use when a user have the default gmail image or have no image at all. What do you guys think? @karolsojko @jkbdbrnwsk @ryanchartrand @jacekelgda

### CODE REVIEW

**Comment by szymonmichalak** [comment]
That looks really good @kdemoya ! /fives

👍 for having a different default image. btw. are they retrieved from our X-Team Google account? strange that mine doesn't show up...

**Comment by kdemoya** [comment]
Thanks @szymonmichalak!, They are pulled from Google and saved, but looks like it's only saving the first picture it pulled and is not updating on each login.

**Comment by kdemoya** [comment]
Added `UserCard` component to the new skill view by the mighty @rmariuzzo. See https://github.com/x-team/unleash/pull/257

image

**Comment by jkbdbrnwsk** [comment]
Looks awesome, @kdemoya! Keep on rocking, man!

**Comment by karolsojko** [comment]
another great piece of work @kdemoya !! 💪

**Pull request merged**
