### PR TITLE
Switch to full names in email notifications

### PR DESCRIPTION
**Pull request by theanxy**
- Related to #98

### CODE REVIEW

**Comment by theanxy** [comment]
Deployed to `QA` for testing.

**Comment by theanxy** [comment]
Found one minor area for improvement: switching to full name in the recipient address. Fixing now
cloudup-58100797-167a-4733-8883-ca1d890e34ff

**Comment by theanxy** [comment]
Deployed to `QA`. Following emails have been triggered from there. @jkbdbrnwsk to confirm if all looks correct.

screen shot 2016-02-22 at 16 15 56

**Comment by jkbdbrnwsk** [comment]
Looks good, thanks, Wojtek!

**Comment by jkbdbrnwsk** [comment]
Actually... could we please replace "step" with "goal" just for the sake of consistency? :prettyplease: Thanks!

**Pull request merged**
