### PR TITLE
Issue #69 - cards with description in path edit

### PR DESCRIPTION
**Pull request by szymonmichalak**
As asked in issue #69, I added a description of a card.

Note: @kbdbrnwsk asked me to add the descriptions on both sides (template cards and cards in drop area). I had to enlarge the cards, as agreed with @kbdbrnwsk.

screen shot 2015-06-09 at 15 47 21

### CODE REVIEW

**Comment by kbdbrnwsk** [comment]
Thanks, @szymonmichalak!

**Comment by theanxy** [comment]
Looks great to me!

**Comment by kbdbrnwsk** [comment]
To me as well... except this little tiny glitch ;-)

screenshot 2015-06-24 23 40 33

Thank you!

**Comment by theanxy** [comment]
I couldn’t reproduce this issue, but I increased the spacing for the drop area anyway, so it will look better now :sparkles:

**Comment by szymonmichalak** [comment]
@theanxy this happens when there are many cards - CSS bottom value of this "Drop area" text is set in %.

**Pull request merged**
