### PR TITLE
Make Linters Great Again

### PR DESCRIPTION
**Pull request by kdemoya**
So... This is a terraform of the linters, I'm getting us up to date to the new enforced rules and also standardized the propTypes and a bit of the app state.

New rules enforced are:

# [import/first](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/first.md)
> This rule reports any imports that come after non-import statements and any absolute imports (i.e. packages) that come after any relative imports.

```javascript
import foo from 'foo'
import bar from './bar'
import * as _ from 'lodash' // <- Must come before './bar'
```

# [comma-dangle](http://eslint.org/docs/rules/comma-dangle)
> Trailing commas simplify adding and removing items to objects and arrays, since only the lines you are modifying must be touched. Another argument in favor of trailing commas is that it improves the clarity of diffs when an item is added or removed from an object or array

```javascript
const foo = {
    bar: "baz",
    qux: "quux" // <- Must have trailing comma.
};
```
# [arrow-parens](http://eslint.org/docs/rules/arrow-parens)
> Arrow functions can omit parentheses when they have exactly one parameter and don't return a block. In all other cases the parameter(s) must be wrapped in parentheses. This rule enforces the consistent use of parentheses in arrow functions.

```javascript
// Bad
foo => { ... }
(foo) => foo.bar


// Good
foo => foo.bar
(foo) => { ... }

foo => ( 
  <Bar>
    <Foo bar={foo} />
  </Bar>
)
```
# [react/jsx-indent](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-indent.md)
>This rule is aimed to enforce consistent indentation style. The default style is 4 spaces.

The following patterns are bad:

```javascript
// 2 spaces indentation
<App>
  <Hello />
</App>

// no indentation
<App>
<Hello />
</App>

// 1 tab indentation
<App>
  <Hello />
</App>
```

# [react/no-children-prop](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-children-prop.md)
>Children should always be actual children, the children should be nested between the opening and closing tags, not passed in as a prop.

```javascript
// Bad
<MyComponent children={<AnotherComponent />} />
<MyComponent children={['Child 1', 'Child 2']} />


// Good
<MyComponent>Children</MyComponent>

<MyComponent>
  <span>Child 1</span>
  <span>Child 2</span>
</MyComponent>
```

# [react/forbid-prop-types](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/forbid-prop-types.md)
>This rule prevents vague prop types with more specific alternatives available (`any`, `array`, `object`). The defaults are chosen because they have obvious replacements. `any` should be replaced with, well, anything. `array` and `object` can be replaced with `arrayOf` and `shape`, respectively, this encourages prop types that more specifically document their usage.

```javascript
 // Bad 
Component.propTypes = {
  commit: React.PropTypes.any,
  push: React.PropTypes.array,
  unleash: React.PropTypes.object,
};

// Good
Component.propTypes = {
  commit: React.PropTypes.bool,
  push: React.PropTypes.arrayOf(React.PropTypes.number),
  unleash: React.PropTypes.shape({
    foo: React.PropTypes.string,
    bar: React.PropTypes.number,
  }),
};
```

# [react/self-closing-comp](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/self-closing-comp.md)
>Components without children can be self-closed to avoid unnecessary extra closing tag.

```javascript
// Bad
<Foo></Foo>

// Good
<Foo />
<Foo>bar</Foo>
```
# [react/no-unused-prop-types](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unused-prop-types.md)
>Fails if you have defined a prop type but it is never being used anywhere.

```javascript
// Bad
class Hello extends Component{
  render: function() {
    return <div>Hello Bob</div>;
  }
}

Hello.propTypes: {
  name: React.PropTypes.string
}


// Good
class Hello extends Component{
  render: function() {
    return <div>Hello {this.props.name}</div>;
  }
}

Hello.propTypes: {
  name: React.PropTypes.string
}
```

# [react/jsx-filename-extension](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-filename-extension.md)
> Restrict JSX usage only to files with `.jsx` extension.

```javascript
// Bad: MyComponent.js
function MyComponent() {
  return <div />;
}

// Good: MyComponent.jsx
function MyComponent() {
  return <div />;
}
```

### CODE REVIEW

**Comment by karolsojko** [comment]
@kdemoya can you rebase the PR :) ?

**Comment by karolsojko** [comment]
ping ping @kdemoya - it's getting more and more outdated ;P

**Comment by kdemoya** [comment]
@karolsojko Up to date! 😁

**Comment by kdemoya** [comment]
Updated this, should be ready to merge. 

I personally still prefer them @szymonmichalak, I'd vote for keeping them unless they removal get's enforced by default.

**Pull request merged**
