### PR TITLE
Only mount app directory as container volume

### PR DESCRIPTION
**Pull request by jenriquejr**

### CODE REVIEW

**Comment by jenriquejr** [comment]
docker-fix

**Comment by karolsojko** [comment]
Installing dependencies won't work after this change. Try removing your `node_modules` and doing as in README `docker-compose run web yarn` - I suggest closing this PR

**Comment by jenriquejr** [comment]
@karolsojko I did remove the container and images, rebuilt everything  - is that still fixed with `docker-compose run web yarn` because I see `RUN yarn` in the Dockerfile and it didn't seem to have worked

**Comment by jenriquejr** [comment]
@karolsojko - this change came up of the following scenario..
if you clone unleash repo for the first time (meaning there are no images/containers of it) neither a `node_modules` directory in your local machine then you proceed to to the docker build or just `docker-compose up` you will end up with modules installed in the unleash container and that directory being overriden by this line in docker-compose file `volumes: - .:/var/www/unleash`
meaning `node_modules` installed in the container are no longer accessible because the container will look for it in your machine directory - causing the error I show in the image above.

what we are looking for by adding the volumes line above is to be able to work on this files directly and that the container can pick them up that's why I updated it to `volumes: - ./app:/var/www/unleash/app` (everything under app directory is picked up by the container)

**Comment by karolsojko** [comment]
@jenriquejr that's why the instruction in README says to do `docker-compose run web yarn` in order to install the dependencies locally. Keep in mind docker-compose is used only for local development purposes.

Additionally if that change was merged and you wanted to install a new depenedency during your development like f.e. `docker-compose run web yarn add some-package` then the package would not install - thus this change cannot be merged.

**Comment by jenriquejr** [comment]
now I understand, thanks @karolsojko

**Pull request closed without merging**
