### PR TITLE
Added proposal for skill's resources.

### LINKED ISSUE #269: Skill resources
Propose a design and implementation with mocked data for a list of resources on a given skill (the single skill view).

A resource consists of a title, short description and url.

Synopsis:
X-Teamers are sharing a ton of useful links on Slack every week. The idea is to keep collecting them in one place, categorize them - and then let users rate them.

Eg. “Looking for an Angular course? Here is a list of 10 websites that might suit your needs. We provide you with a brief description - and our users’ rating.”

### PR DESCRIPTION
**Pull request by rmariuzzo**
**DO NOT MERGE**

## Concept

The idea is to show resources in a second plane after profiles. Using tabs
we can achieve this separation of contents. 

## Features 

 - [x] The resources could be a list of links that can be of different kind (blog post, course, video, etc…).
 - [x] Any resource can receive upvotes by users to make them more relevant based on user votes.
 - [x] Resources will be sorted by upvotes `Z-A`.
 - [ ] User should be able to add resources.
    - [ ] The URL should be valid, and a proper should be selected.
    - [ ] The user cannot edit the URL only the type **Need feedback**.
 - [ ] User should be able to remove own or any resources.

## Video <sup><sub>Click on image</sub></sup>

[maxresdefault](https://youtu.be/FfE_JODRHJk)

# 💁 Please, add your feedback on everything.

---

This could/eventually closes #269.

### CODE REVIEW

**Comment by rmariuzzo** [comment]
@x-team/unleash I would be happy to get some feedback.

**Comment by karolsojko** [comment]
@rmariuzzo I LOOOVE this idea 👍  ❤️ 

I've created 4 quick-win tasks that will implement all the rest (#289, #290, #291, #292) - and we can merge this one as it is - what do you say @rmariuzzo ? (just needs rebasing).

**Comment by rmariuzzo** [comment]
@karolsojko I rebased with latest `develop`.

**Comment by rmariuzzo** [comment]
Thank you @karolsojko 🙇

**Pull request merged**
