### PR TITLE
User Path styling - fixes #225

### LINKED ISSUE #225: Style user's paths list
This is blocked until #224 is resolved!

Style the multiple paths of one user (with goals) into something similar to this: 

image

this is just a reference - you can implement something more fancy ;)

### PR DESCRIPTION
**Pull request by kdemoya**
-Added styling for the user Path.
-Created `GoalCard` component, just pass the `goal` object as the API returns it to render a goal card anywhere.

image

### CODE REVIEW

**Comment by rmariuzzo** [comment]
It looks awesome @kdemoya!

**Comment by diegodurli** [comment]
Beautiful work @kdemoya! 👏

**Comment by ryanchartrand** [comment]
Wow @kdemoya, awesome seeing you get to use your design and code skills together on this app :) This looks really slick.

Since you've stumbled into getting to play with our new branding style, I want to share our brand new styleguide with you: https://docs.google.com/presentation/d/1Ohb39_BKj_KUcZvkS49gcGsU5Bw2wxCrMrAqSjz_fxA/edit#slide=id.g16d21eb627_0_10

If we're going to use green for 'marked as achieved', we don't have greens in the style pallette, but perhaps these might work better? https://coolors.co/ff5964-56e39f-59cd90-a0eec0-8fd694 

Also with the styleguide, we like to have extra breathing room/white space, so perhaps adding some padding on the cards to give the icons that extra white space could help too.

Really great work, let's make this ready for merge :)

**Comment by karolsojko** [comment]
amazin @kdemoya 👍  - let's just adjust to the comments Ryan posted and we're good to go :)

**Comment by jkbdbrnwsk** [comment]
This looks awesome, @kdemoya!

There will be quite a few new features in the Unleash 2.0 - and if you were willing to lend us your crazy design skillz, that would be awesome and much, much appreciated!

**Comment by kdemoya** [comment]
I absolutely agree @ryanchartrand, thanks for the style guide, it helps a lot!

@jkbdbrnwsk Thanks, it would be my pleasure. :)

**Comment by kdemoya** [comment]
**New**
-Tweaked green color.
-Added more breathing space.

image

cc @ryanchartrand @karolsojko @jkbdbrnwsk

**Comment by jacekelgda** [comment]
Looks good :)

**Pull request merged**
