### PR TITLE
Refactor drag&drop, Issue #42 and #62

### PR DESCRIPTION
**Pull request by szymonmichalak**

### CODE REVIEW

**Comment by theanxy** [comment]
I’ll take a look :)

P.S. Tests are failing, so I think you will need to update these as well.

**Comment by szymonmichalak** [comment]
Updated, thanks!

**Comment by theanxy** [comment]
This looks good :-) Great job. Just two notes.

### Duplicating cards problem
When I’m trying to drag an existing card in the drop area, just after I start the dragging action, the card is getting duplicated.
screenshot_31_05_15_14_40

Please note that library demos don’t mimic this behavior.
screenshot_31_05_15_14_44

### Filtering out already used templates in the 'user edit' screen
I suppose this was requested by Kuba?

Thanks,
Wojtek

**Comment by theanxy** [comment]
Deployed branch `b-drag-and-drop` to http://staging.unleash.x-team.com/ for review purposes.

**Comment by szymonmichalak** [comment]
**Duplicated cards problem** is now solved (it was only CSS issue to hide the 'source' of dragging).

**Filtering out already used templates** - Yes, issue #57

**Comment by theanxy** [comment]
Redeployed to http://staging.unleash.x-team.com/. Looks good to me. @Kuba can you sign off?

**Comment by kbdbrnwsk** [comment]
Signing off. :+1: : :) Thanks!

**Pull request merged**
