### PR TITLE
Google Sign In - Fixes #213

### LINKED ISSUE #213: Google Sign-in
Create a google sign-in workflow together with Profiles API - look for version 1.x as a reference point.

### PR DESCRIPTION
**Pull request by williamcabrera4**
-Added AuthService for Google Auth.
-Added Firebase for Google Provider Auth.
-Added User reducer, action creators and constants.
-Added Redux Toast to display message.
-Added Immutable JS
-Added user sign in.
-Added user register.

### CODE REVIEW

**Comment by williamcabrera4** [comment]
Login Screen
screen shot 2016-09-18 at 1 03 38 am

Success Login
screen shot 2016-09-18 at 1 04 43 am

Login without an X-Team email
screen shot 2016-09-18 at 1 04 16 am

**Comment by karolsojko** [comment]
hmm just a quick question @williamcabrera4 - we don't use Firebase for quite a while now - what is it for?

**Comment by karolsojko** [comment]
@williamcabrera4 since I need to set the Firebase key in environment variables on stagign - it's better for the config to have a flat strucutre. Now the `firebaseConfig` key demands an object and it's not possible to set it in the environment variables - other than that everything looks AWESOME 👍 💪

**Comment by williamcabrera4** [comment]
Hey @karolsojko we're now ready for the action!
 ` firebaseApiKey: ''`
  `firebaseAuthDomain: ''`
  `firebaseDatabaseURL: ''`
  `firebaseStorageBucket: ''`
  `firebaseMessagingSenderId: ''`

**Pull request merged**
